#! /bin/sh

update_db_scripts(){
    sed -i "" -e "/_localurl/$localurl/" -e "/_localpath/$localpath/" -e "/_developmenthost/$devhost/" -e "/_developmentremoteurl/$devurl/" -e "/_developmentremotepath/$devpath/" -e "/_staginghost/$staginghost/" -e "/_stagingremoteurl/$stagingurl/" -e "/_stagingremotepath/$stagingpath/" -e "/_productionhost/$productionhost/" -e "/_productionremoteurl/$productionurl/" -e "/_productionremotepath/$productionpath/" $1
}

echo 'Removing Config and Database from Git'
git rm --cached ee/expressionengine/config/config.php &> /dev/null
git rm --cached ee/expressionengine/config/database.php &> /dev/null
git rm -r --cached webroot/images &> /dev/null
echo 'Ignoring Config and Database'
sed -i '' -e '$a\
    *\/expressionengine\/config\/config.php\
    *\/expressionengine\/config\/database.php\
    \
    #Images\
    \
    *\/images\/\' .gitignore
echo 'Setting permissions on config file'
chmod 666 ee/expressionengine/config/config.php
echo 'Creating EE Cache'
mkdir ee/expressionengine/cache
echo 'Setting full permissions on EE Cache'
chmod 777 ee/expressionengine/cache
echo 'Setting full permissions images folder and all sub folders'
chmod -R 777 webroot/images
echo 'Setting permissions on templates'
chmod -R 777 webroot/assets/templates
echo 'Finding apache group...'
APACHE=$(ps axho user,comm|grep -E "httpd|apache"|uniq|grep -v "root"|awk 'END {if ($1) print $1}' | xargs groups | awk 'END {if ($2 == ":") { print $3 } else { print $1 }}')
echo "Apache group is $APACHE."
echo "Granting permissions to Apache."
sudo chgrp -R $APACHE .
echo "Setting up DB Scripts."
echo "Local Settings:"
read -e -p "    Enter the local url: " localurl
read -e -p "    Enter the local path: " localpath
echo "Dev Server Settings:"
read -e -p "    Enter SSH Dev Hostname: " devhost
read -e -p "    Enter Dev URL: " devurl
read -e -p "    Enter Dev Path: " devpath
read -e -p "    Enter Dev Database Name: " devdb
echo "Staging Server Settings:"
read -e -p "    Enter SSH Staging Hostname: " staginghost
read -e -p "    Enter Staging URL: " stagingurl
read -e -p "    Enter Staging Path: " stagingpath
read -e -p "    Enter Staging Database Name: " stagingdb
read -e -p "    Enter Staging Database User: " stagingdbuser
read -e -p "    Enter Staging Database Pass: " stagingdbpass
echo "Production Server Settings:"
read -e -p "    Enter SSH Dev Hostname: " productionhost
read -e -p "    Enter Production URL: " productionurl
read -e -p "    Enter Production Path: " productionpath
read -e -p "    Enter Production Database Name: " productiondb
read -e -p "    Enter Production Database User: " productiondbuser
read -e -p "    Enter Production Database Pass: " productiondbpass
echo "Updating DB Scripts."
update_db_scripts ./bak/export
update_db_scripts ./bak/import
echo "Updating Config File."
sed -i '' -e "/_devdb/$devdb/" -e "/_stagingdb/$stagingdb/" -e "/_staginguser/$stagingdbuser/" -e "/_stagingpass/$stagingdbpass/" -e "/_productiondb/$productiondb/" -e "/_productionuser/$productiondbuser/" -e "/_productionpass/$productiondbpass/" cfg.php

echo "Creating Local DB"
mysql -uroot -proot -e "create database $devdb;"
mysql -uroot -proot $devdb < .bak/sql/db_dump.sql
    
echo "Cleaning up..."
git remote rm origin
echo "Done."
