#!/bin/sh

read_cfg(){
    grep $1 cfg.php | grep $2 | awk 'END { print $3 }' | grep -oE "[^';]+"
}

if [ -z $1 ]; then
    echo "Must specify destination environment."
    echo "One of 'd' for development, 's' for staging, 'p' for production."
    exit 
elif [ $1 == 's' -o $1 == 'p' -o $1 == 'd' ]; then
    LOCALURL='_localurl'
    LOCALPATH='_localpath'
    LOCALDB=$(read_cfg dev database)
    echo "Getting local values"
    echo
    echo "Local Url: $LOCALURL"
    echo "Local Path: $LOCALPATH"
    echo "Local DB: $LOCALDB"
    echo
    if [ $1 == 'd' ]; then
        echo 'Connecting to Development DB'
        HOST='_developmenthost'
        REMOTEURL='_developmentremoteurl'
        REMOTEPATH='_developmentremotepath'
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        REMOTEDB=$(read_cfg dev database)
        REMOTEDBPASS=$(read_cfg dev password)
        REMOTEDBUSER=$(read_cfg dev username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    elif [ $1 == 's' ]; then
        echo 'Connecting to Staging DB'
        HOST='_staginghost'
        REMOTEURL='_stagingremoteurl'
        REMOTEPATH='_stagingremotepath'
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        REMOTEDB=$(read_cfg staging database)
        REMOTEDBPASS=$(read_cfg staging password)
        REMOTEDBUSER=$(read_cfg staging username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    else
        echo 'Connecting to Production DB'
        HOST='_productionhost'
        REMOTEURL='_productionremoteurl'
        REMOTEPATH='_productionremotepath'
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        REMOTEDB=$(read_cfg production database)
        REMOTEDBPASS=$(read_cfg production password)
        REMOTEDBUSER=$(read_cfg production username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    fi
    echo 'Issuing Command'
    mysqldump -uroot -proot $LOCALDB | sed -e "s+$LOCALPATH+$REMOTEPATH+g" -e "s+$LOCALURL+$REMOTEURL+g" | gzip -9 | ssh $HOST "gzip -d | mysql -u$REMOTEDBUSER -p$REMOTEDBPASS $REMOTEDB"
fi
