#!/bin/sh

read_cfg(){
    grep $1 cfg.php | grep $2 | awk 'END { print $3 }' | grep -oE "[^';]+"
}

if [ -z $1 ]; then
    echo "Must specify destination environment."
    echo "One of 'd' for development, 's' for staging, 'p' for production."
    exit 
elif [ $1 == 's' -o $1 == 'p' -o $1 == 'd' ]; then
    LOCALURL='_localurl'
    LOCALPATH='_localpath'
    LOCALDB=$(read_cfg dev database)
    if [ $1 == 'd' ]; then
        echo 'Connecting to Development DB'
        HOST='_developmenthost'
        REMOTEURL='_developmentremoteurl'
        REMOTEPATH='_developmentremotepath'
        REMOTEDB=$(read_cfg dev database)
        REMOTEDBPASS=$(read_cfg dev password)
        REMOTEDBUSER=$(read_cfg dev username)
    elif [ $1 == 's' ]; then
        echo 'Connecting to Staging DB'
        HOST='_staginghost'
        REMOTEURL='_stagingremoteurl'
        REMOTEPATH='_stagingremotepath'
        REMOTEDB=$(read_cfg staging database)
        REMOTEDBPASS=$(read_cfg staging password)
        REMOTEDBUSER=$(read_cfg staging username)
    else
        echo 'Connecting to Production DB'
        HOST='_productionhost'
        REMOTEURL='_productionremoteurl'
        REMOTEPATH='_productionremotepath'
        REMOTEDB=$(read_cfg production database)
        REMOTEDBPASS=$(read_cfg production password)
        REMOTEDBUSER=$(read_cfg production username)
    fi
    mysqldump -uroot -proot $LOCALDB | sed -e "s+$LOCALPATH+$REMOTEPATH+g" -e "s+$LOCALURL+$REMOTEURL+g" | gzip -9 | ssh $HOST "gzip -d | mysql -u$REMOTEDBUSER -p$REMOTEDBPASS $REMOTEDB"
fi
