#!/bin/sh

read_cfg(){
    grep $1 cfg.php | grep $2 | awk 'END { print $3 }' | grep -oE "[^';]+"
}

if [ -z $1 ]; then
    echo "Must specify source environment."
    echo "One of 'd' for development, 's' for staging, 'p' for production."
    exit 
elif [ $1 == 's' -o $1 == 'p' ]; then
    LOCALURL='principles.dev'
    LOCALPATH='/Library/WebServer/Documents/principles/'
    LOCALDB=$(read_cfg dev database)
    echo "Getting local values"
    echo
    echo "Local Url: $LOCALURL"
    echo "Local Path: $LOCALPATH"
    echo "Local DB: $LOCALDB"
    echo
    echo "Creating Local DB if it doesn't exist..."
    mysql -uroot -proot -e "create database if not exists $LOCALDB;"
    if [ $1 == 'd' ]; then
        echo 'Connecting to Development DB'
        HOST=''
        REMOTEURL=''
        REMOTEPATH=''
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        REMOTEDB=$(read_cfg dev database)
        REMOTEDBPASS=$(read_cfg dev password)
        REMOTEDBUSER=$(read_cfg dev username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    elif [ $1 == 's' ]; then
        echo 'Connecting to Staging DB'
        HOST='wildflower'
        REMOTEURL='http://staging.wildflowermontessorischool.org'
        REMOTEPATH='/var/www/approach/staging/'
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        REMOTEDB=$(read_cfg staging database)
        REMOTEDBPASS=$(read_cfg staging password)
        REMOTEDBUSER=$(read_cfg staging username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    else
        echo
        echo "Host: $HOST"
        echo "Remote URL: $REMOTEURL"
        echo "Remote Path: $REMOTEPATH"
        echo
        echo 'Reading Config File for values'
        echo
        HOST='wildflower'
        REMOTEURL='http://wildflowermontessorischool.org'
        REMOTEPATH='/var/www/approach/production/'
        echo 'Reading Config File for values'
        REMOTEDB=$(read_cfg production database)
        REMOTEDBPASS=$(read_cfg production password)
        REMOTEDBUSER=$(read_cfg production username)
        echo "Remote DB: $REMOTEDB"
        echo "Remote DB password: $REMOTEDBPASS"
        echo "Remote DB user: $REMOTEDBUSER"
        echo
    fi
    echo 'Issuing Command'
    ssh $HOST "mysqldump -u$REMOTEDBUSER -p$REMOTEDBPASS $REMOTEDB | gzip -9" | gzip -d | sed -e "s+$REMOTEPATH+$LOCALPATH+g" -e "s+$REMOTEURL+$LOCALURL+g" | mysql -uroot -proot $LOCALDB
fi
