#!/bin/sh

read_cfg(){
    grep $1 cfg.php | grep $2 | awk 'END { print $3 }' | grep -oE "[^';]+"
}

if [ -z $1 ]; then
    echo "Must specify source environment."
    echo "One of 'd' for development, 's' for staging, 'p' for production."
    exit 
elif [ $1 == 's' -o $1 == 'p' ]; then
    LOCALURL='_localurl'
    LOCALPATH='_localpath'
    LOCALDB=$(read_cfg dev database)
    mysql -uroot -proot -e "create database if not exists $LOCALDB;"
    if [ $1 == 'd' ]; then
        echo 'Connecting to Development DB'
        HOST='_developmenthost'
        REMOTEURL='_developmentremoteurl'
        REMOTEPATH='_developmentremotepath'
        echo 'Reading Config File for values'
        REMOTEDB=$(read_cfg dev database)
        REMOTEDBPASS=$(read_cfg dev password)
        REMOTEDBUSER=$(read_cfg dev username)
    elif [ $1 == 's' ]; then
        echo 'Connecting to Staging DB'
        HOST='_staginghost'
        REMOTEURL='_stagingremoteurl'
        REMOTEPATH='_stagingremotepath'
        echo 'Reading Config File for values'
        REMOTEDB=$(read_cfg staging database)
        REMOTEDBPASS=$(read_cfg staging password)
        REMOTEDBUSER=$(read_cfg staging username)
    else
        echo 'Connecting to Production DB'
        HOST='_productionhost'
        REMOTEURL='_productionremoteurl'
        REMOTEPATH='_productionremotepath'
        echo 'Reading Config File for values'
        REMOTEDB=$(read_cfg production database)
        REMOTEDBPASS=$(read_cfg production password)
        REMOTEDBUSER=$(read_cfg production username)
    fi
    echo 'Issuing Command'
    ssh $HOST "mysqldump -u$REMOTEDBUSER -p$REMOTEDBPASS $REMOTEDB | gzip -9" | gzip -d | sed -e "s+$REMOTEPATH+$LOCALPATH+g" -e "s+$REMOTEURL+$LOCALURL+g" | mysql -uroot -proot $LOCALDB
fi
